server:
  port: 8080
  servlet:
    context-path: /user-center
spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://10.0.8.13:3307/lhc_user_center
          username: root
          password: liu821290375
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://10.0.8.13:3307/lhc_user_center
          username: root
          password: liu821290375
          driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-center
  data:
    redis:
      database: 1
      host: 10.0.8.13
      port: 6380
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
      password: liu821290375
sa-token:
  token-name: token
  #token 超时时间，默认30天
  timeout: 2592000
  #token 活跃度，超过30分钟不活跃失效
  active-timeout: 1800
  #支持同时登录
  is-concurrent: true
  #同一个账号是否共用1个token
  is-share: false
  token-style: uuid
  is-log: true