server:
  port: 8080
  servlet:
    context-path: /user-center
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://10.0.8.13:3307/lhc_user_center
          username: root
          password: liu821290375
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        slave_1:
          url: jdbc:mysql://10.0.8.13:3307/lhc_user_center
          username: root
          password: liu821290375
          driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-center
  data:
    redis:
      database: 1
      host: 10.0.8.13
      port: 6380
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
      password: liu821290375
sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true